apiVersion: operator.openshift.io/v1alpha1
kind: CertManager
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "0"
spec:
  managementState: "Managed"
  # unsupportedConfigOverrides: # Not sure what these actually do so I'm going to try commenting them out for now
  #   controller:
  #     args:
  #       - '--v=2'
  #       - '--cluster-resource-namespace=$(POD_NAMESPACE)'
  #       - '--leader-election-namespace=kube-system'
  #       - '--dns01-recursive-nameservers=8.8.8.8:53'
  #       - '--dns01-recursive-nameservers-only'
  logLevel: Normal
  observedConfig: null
  operatorLogLevel: Normal