apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-operator-namespace.yaml
  - cert-manager-operator-operatorgroup.yaml
  - cert-manager-operator-subscription.yaml
  - cert-manager-config.yaml
  - external-secret.yaml
