apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-trigger-molecule-converge
spec:
  params:
    - name: pullreq-sha
    - name: git-repo-url
    - name: pullreq-repo-full_name
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: github-triggermolecule-converge-run-
    spec:
      pipelineRef:
        name: molecule-converge
      workspaces:
      - name: shared-data
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
      params:
      - name: git-url
        value: $(tt.params.git-repo-url)
      - name: git-revision
        value: $(tt.params.pullreq-sha)
      - name: git-repo-name
        value: $(tt.params.pullreq-repo-full_name)
      - name: molecule-scenario
        value: "kubevirt"