apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github
  namespace: tekton-pipeline-molecule
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: tekton-pipeline-molecule-github-secrets
      metadataPolicy: None
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk-ocp-pull
  target:
    creationPolicy: Owner
    deletionPolicy: Retain