apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - open-cluster-management-namespace.yaml
  - advanced-cluster-management-operatorgroup.yaml
  - advanced-cluster-management-subscription.yaml
  - open-cluster-management:subscription-admin-clusterrolebinding.yaml
  - multiclusterhub-multiclusterhub.yaml
  - agent-agentserviceconfig.yaml
  - provisioning-configuration-provisioning.yaml
