apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openshift-nfd-namespace.yaml
  - openshift-nfd-operatorgroup.yaml
  - nfd-subscription.yaml
  - nfd-instance-nodefeaturediscovery.yaml
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
