apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ansible-automation-platform-namespace.yaml
  - ansible-automation-platform-operatorgroup.yaml
  - ansible-automation-platform-subscription.yaml
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
