apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mapping-nodenetworkconfigurationpolicy.yaml
  - ../../../components/nmstate/

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
