cluster:
  name: sno
  baseDomain: igou.systems
  gitOpsRepo: https://github.com/igou-io/igou-openshift.git
  gitOpsBasePath: config
  trustedCABundle: ""
  openshiftVersion: "4.15"


certManager:
  enabled: true
  apiCert: true
  defaultIngressCert: true
  acmeBase: 'https://acme-v02.api.letsencrypt.org/directory'
  externalSecret:
    name: dns-token
    onePasswordSecretName: dns-token
  solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: credential
            name: dns-token
          email: igou.david@gmail.com
      selector:
        dnsZones:
          - igou.systems
          - sno.igou.systems


monitoring:
  enabled: false
  storageClass: freenas-iscsi-ssd-csi

network:
  hostRouting: false

auth:
  enabled: true
  htpasswdDisplayName: igou
  externalSecret:
    name: htpasswd-secret
    onePasswordSecretName: htpasswd

timesync:
  enabled: false
  ptp:
    enabled: false
    loadKvmModule: false
    device: 'ptp_kvm'
    sourceStratum: 2
  ntpServers:
    - 1.2.3.4

gitops:
  applicationControllerResources: {}
  kustomizeBuildOptions: "--enable-helm"
