cluster:
  name: hub
  baseDomain: igou.systems

monitoring:
  enabled: false
  storageClass: freenas-nvmeof-fast-csi

network:
  hostRouting: false

auth:
  enabled: true
  htpasswdDisplayName: igou
  globalAdmins:
    - igou
  externalSecret:
    name: htpasswd-secret
    onePasswordSecretName: htpasswd

timesync:
  enabled: false
  ptp:
    enabled: false
    loadKvmModule: false
    device: 'ptp_kvm'
    sourceStratum: 2
  ntpServers:
    - 10.10.90.1
