---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - agent-agentserviceconfig.yaml
  - open-cluster-management:subscription-admin-clusterrolebinding.yaml
  - multiclusterhub-multiclusterhub.yaml
  - provisioning-configuration-provisioning.yaml