applications:

  acm-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: open-cluster-management
    source:
      path: components/acm-operator

  acm-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: open-cluster-management
    source:
      path: components/acm-configuration

  external-secrets-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '0'
    destination:
      namespace: external-secrets-operator
    source:
      path: clusters/hub/external-secrets-operator

  lvms-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '0'
    destination:
      namespace: openshift-storage
    source:
      path: clusters/hub/lvms-operator

  democratic-csi:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '10'
    destination:
      namespace: democratic-csi
    source:
      path: components/democratic-csi