applications:

  acm-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: open-cluster-management
    source:
      path: components/acm-operator

  acm-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: open-cluster-management
    source:
      path: components/acm-configuration

  external-secrets-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '0'
    destination:
      namespace: external-secrets-operator
    source:
      path: clusters/hub/external-secrets-operator

  lvms-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '0'
    destination:
      namespace: openshift-storage
    source:
      path: clusters/hub/lvms-operator

  machineconfigs:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '0'
    destination:
      namespace: openshift-machine-config-operator
    source:
      path: clusters/hub/machineconfigs

  democratic-csi:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '10'
    destination:
      namespace: democratic-csi
    source:
      path: components/democratic-csi

  ansible-automation-platform:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '10'
    destination:
      namespace: ansible-automation-platform
    source:
      path: clusters/hub/ansible-automation-platform

  nmstate:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '0'
    destination:
      namespace: nmstate
    source:
      path: clusters/hub/nmstate

  cloudnative-pg:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '0'
    destination:
      namespace: cloudnative-pg
    source:
      path: clusters/hub/cloudnative-pg