apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - casval-namespace.yml
  - casval-pullsecret-externalsecret.yaml
  - casval-bmc-secret-externalsecret.yaml
  - casval-clusterdeployment.yaml
  - casval-agentclusterinstall.yaml
  - casval-infraenv.yaml
  - casval-baremetalhost.yaml
