apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- openshift-storage-namespace.yml
- openshift-storage-operatorgroup.yml
- lvms-subscription.yml
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
