apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-sdk-rh1
spec:
  refreshInterval: 3600
  retrySettings:
    retryInterval: 1h0m0s
  provider:
    onepasswordSDK:
      vault: rh1
      auth:
        serviceAccountSecretRef:
          name: onepassword-token-rh1
          key: token
          namespace: external-secrets-operator