apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: guacd-nonroot-v2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-scc-nonroot-v2
subjects:
- kind: ServiceAccount
  name: guacd
  namespace: guacamole
