apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openshift-nmstate-namespace.yaml
  - nmstate-operatorgroup.yaml
  - nmstate-subscription.yaml
  - nmstate-instance.yaml
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
