apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-pipeline-ansible-builder
resources:
- https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-clone/0.10/git-clone.yaml
- ansible-builder-pipeline.yml
- ansible-builder-task.yml
- tekton-pipeline-ansible-builder-namespace.yml
