apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - advanced-cluster-management-subscription.yaml
  - advanced-cluster-management-operatorgroup.yaml
  - open-cluster-management-namespace.yaml